version: '3.9'

services:
  db:
    image: postgres:12.12
    hostname: ${DB_HOST}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"
      - "./db/data:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DB}
  dba:
    image: dpage/pgadmin4
    depends_on:
      - db
    hostname: ${DBA_HOST}
    volumes:
      - "./pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DBA_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DBA_PASS}
  api:
    build: ./api/
    depends_on:
      - db
    hostname: ${API_HOST}
    volumes:
      - ./api/code:/app
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - FLASK_APP=api
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_DB}
      - POSTGRES_HOSTNAME=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    command: flask run -h 0.0.0.0 -p ${API_PORT}
  consumer:
    build: ./consumer/
    depends_on:
      - api
    hostname: ${CONSUMER_HOST}
    volumes:
      - ./consumer/code:/app
    ports:
      - ${CONSUMER_PORT}:${CONSUMER_PORT}
    environment:
      - FLASK_APP=consumer
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_ENDPOINT=/api/v1/recommend_meal
    command: flask run -h 0.0.0.0 -p ${CONSUMER_PORT}

