version: '3.9'

services:
  db:
    image: postgres:12.12
    hostname: meals-db
    ports:
      - "5432:5432"
    volumes:
      - "./db/data:/var/lib/postgresql/data/"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=web
  dba:
    image: dpage/pgadmin4
    depends_on:
      - db
    hostname: meals-dba
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pass
  api:
    build: ./api/
    depends_on:
      - db
    hostname: meals-recommender
    volumes:
      - ./api/code:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=api
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=web
      - POSTGRES_HOSTNAME=meals-db
      - POSTGRES_PORT=5432
    command: flask run -h 0.0.0.0 -p 5000
  consumer:
    build: ./consumer/
    depends_on:
      - api
    hostname: meals_frontend
    volumes:
      - ./consumer/code:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=consumer
      - API_HOST=meals-recommender
      - API_PORT=5000
      - API_ENDPOINT=/api/v1/recommend_meal
    command: flask run -h 0.0.0.0 -p 80

